### ISSUE TITLE
[ENHANCEMENT] Whitelisted Jobs That Require Vehicles.

### ISSUE THREAD

**Issue by TheAlphaStrain** [Reprieve-RP/feedback#17]
**What feature you want to improve**
(Fishing/Hunting/Bank Robberys/ ect)
Looking to improve on a small, but realistic aspect of RP for any whitelisted job that require vehicles such as EMS, PD and East Coast Customs... perhaps Weazel News too? Unsure about that one.

**How could this feature be improved? Please describe your idea as much as possible**
Right now, as it sits, EMS and Police Officers have the ability to take out a vehicle and if they need fuel or damage their vehicle they just have to go back to the hospital or PD Station, turn the car in and take out a fresh one. No need to repair or refuel. I want to propose that if we, as a person who requires a vehicle for their job, take out a vehicle, that is our vehicle for the shift. Which means you're responsible for refueling it and repairing it as needed. Rather than going back to where you took the vehicle out to "refresh" it. I feel it would bring more RP into the city seeing cops repair their vehicles or getting towed to East Coast Customs or Ambulances stopped at gas stations to refuel 'cause they're just driving around.

**Additional information**
None.

**Comment by llanboy** [comment]
I back this! Makes sense to me as it is more realistic than just putting it in garage and getting a new one etc.

**Comment by ixhal** [comment]
We had this on new chance when I was there and it was a living hell for people, Its out of cops control if the car they are using gets fucked up because of the way some criminals drive, Same with the ambulance not so much criminals but just locals in general, Just so ur aware it would not create much RP because you could just go to Benny's and repair ur car for a cost, as for gas if ur going for a realistic vibe it should not cost you the employee anything to refuel your vehicle and when we forced people to do that on new chance the cops did not like it. Previous experience tells me to stay away from this stuff as there is multiple issues with having it so the vehicle is actually yours, the amount of coding that would have to go into this as well is just not really viable at this stage of the server, It seems like a simple process but its really not It would have to be made so when you get fired the vehicles are taken from you, Would have to put exceptions in places like the millage system because cops cars are going to be none stop on the move, Its unfair to punch the PD and EMS with stuff like that, Would have to do something about the cosmetics, There is also some other reasons I cant go into much publicly because it would be meta-gamed 100% if I said anything about it

**Comment by llanboy** [comment]
Didn't think of it from that perspective. Would be unfair to punish certain jobs.

**Comment by Senate-the-GermanSoupBall** [comment]
I'm not sure I necessarily agree that it's punishing certain jobs... Having persistent, personal vehicles, IMO, is a lot more fun than having random (Mostly) fleet vehicles.

> We had this on New Chance when I was there and it was a living hell for people, It's out of cops' control if the car they are using gets fucked up because of the way some criminals drive. Same with the ambulance, not so much criminals but just locals in general.

While I understand that it's pretty frustrating to drive in the city, no matter what you're avoiding...I feel like that's kind of a GTA thing more than just a police / ems thing... Yes, your car will get damaged and such...unfortunately it happens and it's not necessarily anyone's fault.

> Just so ur aware it would not create much RP because you could just go to Benny's and repair ur car for a cost. As for gas if ur going for a realistic vibe it should not cost you the employee anything to refuel your vehicle and when we forced people to do that on New Chance the cops did not like it.

First off I feel like just having to _go_ to a repair shop creates RP in and of itself...even if you're just there getting an automatic repair. If anything, I feel as if this is a better way to try and create RP because it doesn't _force_ people to do anything more than press a few buttons, if that.

Technically, from a realism standpoint...it's actually more realistic for PD to be responsible for taking care of their cars. As far as I understand IRL and in most departments, the officer is responsible for their car both on and off duty, and for _all_ maintenance. But that's not really the point I want to make...

We all know how a lot of the cops in NC both were and are...I don't think how they acted should influence how this department is treated. I say it would at least be fair to do a vote rather than assume what the people on this server are going to think. I'm from NC, I know how people are treated there, and I'm well aware of how toxic officers can be to other officers AND civilians. But I say let's not let their shitty behavior and personalities ruin _anything_ here for _us_.

> The amount of coding that would have to go into this as well is just not really viable at this stage of the server. It seems like a simple process but it's really not. It would have to be made so that when you get fired the vehicles are taken from you, would have to put exceptions in places like the millage system because cops' cars are going to be none stop on the move. It's unfair to punch the PD and EMS with stuff like that. Would have to do something about the cosmetics.

It doesn't have to be viable at this stage in development to still plan on doing it IMO. And I personally don't think it would really HAVE to feel like it's punching PD and EMS... Going back to my point earlier...sure, you could do something like put mileage exceptions in. But that doesn't have to mean the officer / EMT has to pay for it, right? Also, if cop cars did have to get engine replacements, that could also create some RP IMO. Or they could just be completely exempt from the milage system, there are honestly many ways it could be done. I'm not exactly sure what you mean about cosmetics though...

> There are also some other reasons I can't go into much publicly because it would be meta-gamed 100% if I said anything about it.

I'm gonna be honest...this concerns me. I never did like staying silent about something because of what others will do about it...especially when it inhibits the ability to even talk about an issue or suggestion. Maybe it's just a transparency thing, but in all honesty, transparency is something that's really important to me for a variety of reasons. I understand wanting to stop rule breaks before they happen...but in my personal opinion, people are gonna do what they want to do and think what they want to think. I do not agree that there is any reason, whatsoever, even if I understand it, that the actions of bad actors should influence how a discussion is had, or even IF it's had at all.

Please though, while reading this please keep in mind that I'm only speaking up because I care and want what's best for the city. A lot of my own opinions come from my own personal experience, and what I've come to believe is best practice. I truly love the potential that I'm seeing in what's already in existence and the server isn't even launched yet. That's a good sign to me.

**Comment by BIRLZ95** [comment]
> n

I get it however me personally I expect people to **_roleplay_** and call mechanics for a tow, go fuel their vehicles.. however I suppose alot of the WL jobs have fleets of vehicle which allows them to go get a new one just both sides really. Maybe once the server grows this can be intoduced but right now I don't see think it matters really.

**Comment by Senate-the-GermanSoupBall** [comment]
> 
Maybe once the server grows this can be introduced but right now I don't think it matters really.

Truthfully the main reason I want this is because I feel like it'd be easier to be more immersive and just keep certain things in your trunk/glovebox... I realize you HAVE to do that already, I'm just certain that there will be scenarios where people will forget they had something in their glovebox or trunk, and lose said thing. Granted this isn't a massive issue, so honestly, I think of this issue as more of a quality-of-life one. Definitely, something to consider later, but still something to consider.

**Comment by ixhal** [comment]
Going to close this since its a very niche thing and the majority of people don't have a issue with the current systems in place.
