### ISSUE TITLE
Mining Bug

### ISSUE THREAD

**Issue by Zeeksey** [Reprieve-RP/feedback#9]
When going mining it shows "my eye caught something shiny" but it doesn't show anything shining, I just gotta walk around and see when it says to press E

- Add popped out ore nodes that you can go up to and mine
- Add a visual effect to show the shining spot

**Comment by ixhal** [comment]
I have a idea for this moving forward but for the moment we will just have to suffer with it as its not a huge priority!
The idea is have is to create some gem objects and have them spawn in the cave in the places where you need to mind but instead of the pop up gems will be highly visible and you will look at it with your 3rd eye, It will probably end up being a good buff to mining also but it will require a little bit of work creating the models and actually coding it, but I'm 100% committed to changing it to something like this in the future when time allows it
